//! Streaming events emitted by [`LanguageModel::stream`](crate::LanguageModel::stream).

use serde::{Deserialize, Serialize};

/// Token-usage accounting for a single turn.
///
/// All fields are best-effort: providers that do not report a particular
/// counter set it to `0`. Cached vs. uncached input tokens are split out so
/// callers can compute cost-aware budgets without provider-specific code.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Usage {
    /// Input tokens billed at the standard rate (not served from cache).
    pub input_tokens: u32,
    /// Output tokens generated by the model.
    pub output_tokens: u32,
    /// Input tokens served from a provider-side prompt cache, if any.
    pub cached_input_tokens: u32,
}

/// Why a generation ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum FinishReason {
    /// Model produced a complete response on its own.
    Stop,
    /// `max_tokens` reached before the model finished.
    Length,
    /// Model decided to invoke one or more tools; caller should run them and
    /// loop back with the results.
    ToolUse,
    /// Provider safety/content filter halted generation.
    ContentFilter,
    /// Caller cancelled via the supplied cancellation token.
    Cancelled,
    /// Anything else (provider-specific). The provider may surface detail via
    /// `provider_metadata` on the request side or via tracing.
    Other,
}

/// A single chunk of a streamed model response.
///
/// Streams are guaranteed to end with exactly one `Finish` or `Error` event.
/// All variants are `#[non_exhaustive]` to allow additive evolution.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum LanguageModelEvent {
    /// A delta of generated text.
    TextDelta {
        /// Text fragment to append to the assistant message in progress.
        delta: String,
    },

    /// A delta of reasoning trace (e.g. Anthropic extended thinking).
    ReasoningDelta {
        /// Reasoning fragment.
        delta: String,
    },

    /// The model has begun invoking a tool. `input` is empty here; argument
    /// JSON arrives as one or more [`Self::ToolCallDelta`] events and is
    /// finalized by [`Self::ToolCallEnd`].
    ToolCallStart {
        /// Provider-assigned tool-call identifier (correlates with `tool_use_id`).
        id: String,
        /// Tool name, matching one of the request's [`ToolSpec`](crate::ToolSpec)s.
        name: String,
    },

    /// A delta of the tool's JSON-encoded arguments. Concatenating the
    /// `arguments_delta` fields between `ToolCallStart` and `ToolCallEnd`
    /// for a given `id` yields the complete arguments JSON string.
    ToolCallDelta {
        /// Identifier of the in-flight tool call.
        id: String,
        /// Partial JSON-encoded arguments. May not parse on its own.
        arguments_delta: String,
    },

    /// Tool-call argument streaming is complete for `id`. Implementations may
    /// emit the fully-parsed arguments here for callers that prefer not to
    /// reassemble the deltas.
    ToolCallEnd {
        /// Identifier of the completed tool call.
        id: String,
        /// Fully-parsed arguments JSON, if the provider supplied it.
        arguments: Option<serde_json::Value>,
    },

    /// Generation is finished. This is always the last event in a successful
    /// stream.
    Finish {
        /// Why the generation stopped.
        reason: FinishReason,
        /// Token usage for the turn.
        usage: Usage,
    },

    /// Terminal error event. No further events will follow.
    Error {
        /// Provider-emitted error message.
        message: String,
    },
}
