//! `#[tool]` proc-macro expansion.
//!
//! Turns an `async fn foo(p1: T1, p2: T2) -> Result<ToolResult, AgentError>`
//! into a zero-sized type `foo` that implements [`agent_sdk_core::Tool`].
//!
//! Generated items:
//! 1. A private `__<fn>_Params` struct deriving `Deserialize` + `JsonSchema`,
//!    one field per fn parameter (forwarding doc attrs and `#[serde(...)]`).
//! 2. The original async fn, renamed `__<fn>_inner`, kept verbatim so callers
//!    can still use the typed signature directly.
//! 3. A unit struct with the original fn name (e.g. `foo`) plus an
//!    `impl agent_sdk_core::Tool` block dispatching to the inner fn.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{
    parse2, spanned::Spanned, AttrStyle, Attribute, FnArg, Ident, ItemFn, Pat, PatType, Visibility,
};

use crate::docs;

pub(crate) fn expand(_attr: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let func: ItemFn = parse2(item)?;
    validate(&func)?;

    let fn_name = func.sig.ident.clone();
    let fn_vis = func.vis.clone();
    let fn_desc = docs::extract(&func.attrs).unwrap_or_else(|| fn_name.to_string());
    let tool_name = fn_name.to_string();

    let inner_ident = format_ident!("__{}_inner", fn_name);
    let params_ident = format_ident!("__{}_Params", fn_name);

    let params = collect_params(&func)?;

    let field_defs = params.iter().map(|p| {
        let name = &p.ident;
        let ty = &p.ty;
        let attrs = &p.attrs;
        quote! {
            #(#attrs)*
            pub #name: #ty,
        }
    });

    let call_args = params.iter().map(|p| {
        let name = &p.ident;
        quote!(__args.#name)
    });

    // Inner fn = original fn with `pub(crate)` vis so the impl can call it.
    // Strip param attributes (they live on the params struct instead).
    let mut inner_fn = func.clone();
    inner_fn.sig.ident = inner_ident.clone();
    inner_fn.vis = Visibility::Inherited;
    for input in inner_fn.sig.inputs.iter_mut() {
        if let FnArg::Typed(pt) = input {
            pt.attrs.clear();
        }
    }

    // Public type carrying the original fn name; ergonomic `pub use` from
    // user crates. The unit value `foo` itself is the registrable Tool.
    let type_doc = format!("Tool handle generated by `#[tool]` for `{fn_name}`.");

    let expanded = quote! {
        #[doc(hidden)]
        #[derive(::agent_sdk_core::__macros::serde::Deserialize, ::agent_sdk_core::__macros::schemars::JsonSchema)]
        #[serde(crate = "::agent_sdk_core::__macros::serde")]
        #[schemars(crate = "::agent_sdk_core::__macros::schemars")]
        #[allow(non_camel_case_types, non_snake_case)]
        struct #params_ident {
            #(#field_defs)*
        }

        #[allow(non_snake_case)]
        #inner_fn

        #[doc = #type_doc]
        #[derive(Debug, Default, Clone, Copy)]
        #[allow(non_camel_case_types)]
        #fn_vis struct #fn_name;

        #[::agent_sdk_core::__macros::async_trait::async_trait]
        impl ::agent_sdk_core::Tool for #fn_name {
            fn name(&self) -> &str { #tool_name }
            fn description(&self) -> &str { #fn_desc }
            fn input_schema(&self) -> ::agent_sdk_core::__macros::serde_json::Value {
                let schema = ::agent_sdk_core::__macros::schemars::schema_for!(#params_ident);
                ::agent_sdk_core::__macros::serde_json::to_value(&schema)
                    .expect("schemars schema must serialize to JSON")
            }
            async fn execute(
                &self,
                arguments: ::agent_sdk_core::__macros::serde_json::Value,
                _cancel: ::agent_sdk_core::__macros::tokio_util::sync::CancellationToken,
            ) -> ::core::result::Result<
                ::agent_sdk_core::ToolResult,
                ::agent_sdk_core::AgentError,
            > {
                let __args: #params_ident = ::agent_sdk_core::__macros::serde_json::from_value(arguments)
                    .map_err(|e| ::agent_sdk_core::AgentError::InvalidToolArguments {
                        name: #tool_name.to_string(),
                        message: e.to_string(),
                    })?;
                #inner_ident( #(#call_args),* ).await
            }
        }
    };

    Ok(expanded)
}

struct Param {
    ident: Ident,
    ty: syn::Type,
    attrs: Vec<Attribute>,
}

fn collect_params(func: &ItemFn) -> syn::Result<Vec<Param>> {
    let mut out = Vec::new();
    for input in &func.sig.inputs {
        let FnArg::Typed(PatType { pat, ty, attrs, .. }) = input else {
            return Err(syn::Error::new(
                input.span(),
                "#[tool] does not support `self` receivers; use a free function",
            ));
        };
        let Pat::Ident(ident_pat) = pat.as_ref() else {
            return Err(syn::Error::new(
                pat.span(),
                "#[tool] parameters must be simple identifiers (no patterns)",
            ));
        };
        if let syn::Type::Reference(_) = ty.as_ref() {
            return Err(syn::Error::new(
                ty.span(),
                "#[tool] parameters cannot be references; use owned types",
            ));
        }
        // Forward `///` doc comments + `#[serde(...)]` / `#[schemars(...)]`
        // attrs to the generated struct field. Filter the rest to avoid
        // surprising downstream attributes leaking through.
        let mut forwarded = Vec::new();
        for a in attrs {
            if matches!(a.style, AttrStyle::Outer)
                && (a.path().is_ident("doc")
                    || a.path().is_ident("serde")
                    || a.path().is_ident("schemars"))
            {
                forwarded.push(a.clone());
            }
        }
        out.push(Param {
            ident: ident_pat.ident.clone(),
            ty: ty.as_ref().clone(),
            attrs: forwarded,
        });
    }
    Ok(out)
}

fn validate(func: &ItemFn) -> syn::Result<()> {
    if func.sig.asyncness.is_none() {
        return Err(syn::Error::new(
            func.sig.fn_token.span(),
            "#[tool] requires an `async fn`",
        ));
    }
    if !func.sig.generics.params.is_empty() {
        return Err(syn::Error::new(
            func.sig.generics.span(),
            "#[tool] does not support generic parameters",
        ));
    }
    if let Some(wc) = &func.sig.generics.where_clause {
        return Err(syn::Error::new(
            wc.where_token.span(),
            "#[tool] does not support `where` clauses",
        ));
    }
    // Reject `unsafe fn`, `const fn`, `extern fn` — none make sense for a Tool.
    if let Some(unsafety) = &func.sig.unsafety {
        return Err(syn::Error::new(unsafety.span(), "#[tool] cannot be `unsafe`"));
    }
    if let Some(constness) = &func.sig.constness {
        return Err(syn::Error::new(constness.span(), "#[tool] cannot be `const`"));
    }
    Ok(())
}

